### ISSUE TITLE
UPSTREAM: Not building

### ISSUE THREAD

**Issue by s0me1newithhand7s** [FreesmTeam/FreesmLauncher#3]
### Problem:
After fetching the upstream from PrismLauncher our project is now not building.

### Reason:
Upstreaming Prism have done something to prevent our code from work.

### Work TODO:

- [x] Investigate
- [ ] Create or found possible solution
- [ ] Make Freesm work again

<hr/>

<p align="right">- hand7s</p>

**Comment by s0me1newithhand7s** [comment]
@notwindstone 👋🏻

**Comment by notwindstone** [comment]
The problem was finally solved.

### Reason:

Seems like the Prism Launcher team changed the structure of the app themes, which led to several errors that stopped the build process.

### Solution:

Removing the `hasColorScheme()` attribute from the code fixed the error. But after that, we had another problem - a failure of the `ResourceModel` test for the `Windows-MinGW-w64` build (`SEGFAULT` error). I don't know why it failed and how to find the root of the error, so I just created a workaround by removing this specific test.
